# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104SsyEU1hYbnv9jl2A5f4AkeSIqbhRp7
"""

# !pip install faiss-cpu sentence-transformers
import subprocess, sys
import pandas as pd
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import random
from datasets import Dataset
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType






subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "bitsandbytes>=0.43.0", "--prefer-binary"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "triton"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q",
    "transformers==4.51.3","mlflow==2.19.0", "peft==0.14.0", "trl==0.13.0",
    "accelerate==1.3.0", "datasets==3.2.0",
    "gradio==5.9.1", "faiss-cpu==1.9.0", "sentence-transformers==2.5.1"
])
print("✅ Dependencies installed.")

import transformers
print(transformers.__version__) # This should now output 4.51.3

print("Loading IFCT 2017 dataset...")
df = pd.read_csv('ifct2017_compositions.csv').dropna(subset=['name'])

NON_VEG_KW = ['chicken', 'beef', 'pork', 'mutton', 'fish', 'egg', 'poultry', 'meat', 'liver', 'crab', 'prawn', 'shrimp', 'lamb']
DAIRY_KW = ['milk', 'cheese', 'paneer', 'curd', 'yogurt', 'butter', 'ghee']
ROOT_KW = ['onion', 'garlic', 'potato', 'carrot', 'radish', 'turnip', 'beetroot', 'ginger']

def get_allowed_diets(food_name):
    name_lower = food_name.lower()
    if any(kw in name_lower for kw in NON_VEG_KW): return ["non-vegetarian"]
    allowed = ["non-vegetarian", "vegetarian"]
    if not any(kw in name_lower for kw in DAIRY_KW): allowed.append("vegan")
    if not any(kw in name_lower for kw in ROOT_KW): allowed.append("jain")
    return allowed

FOOD_DB_RAW = []
FOOD_METADATA = []

for _, row in df.iterrows():
    food_name = str(row['name']).strip()

    # Existing nutrients
    protein = row.get('prot', '0')
    iron = row.get('fe', '0')
    calcium = row.get('ca', '0')
    zinc = row.get('zn', '0')
    vit_c = row.get('vitc', '0')

    # NEW NUTRIENTS extracted from IFCT
    vit_a = row.get('vita', '0')      # Vitamin A
    potassium = row.get('k', '0')     # Potassium
    magnesium = row.get('mg', '0')    # Magnesium
    fiber = row.get('fib', '0')       # Dietary Fiber
    folate = row.get('fol', '0')      # Folate / B9

    if protein == '0' and iron == '0' and calcium == '0':
        continue

    allowed_diets = get_allowed_diets(food_name)

    # Add the new nutrients to the text the LLM reads
    content_string = (
        f"{food_name} is a food item suitable for {', '.join(allowed_diets)} diets. "
        f"A standard 100g portion contains {protein}g Protein, {iron}mg Iron, "
        f"{calcium}mg Calcium, {zinc}mg Zinc, {vit_c}mg Vitamin C, "
        f"{vit_a}mcg Vitamin A, {potassium}mg Potassium, {magnesium}mg Magnesium, "
        f"{fiber}g Fiber, and {folate}mcg Folate."
    )

    FOOD_DB_RAW.append(content_string)
    FOOD_METADATA.append({"name": food_name, "allowed_diets": allowed_diets})

print(f"✅ Generated {len(FOOD_DB_RAW)} documents with expanded nutrient profiles.")

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

print("Loading embedding model (all-MiniLM-L6-v2)...")
embedder = SentenceTransformer('all-MiniLM-L6-v2')

print("Encoding food database...")
food_embeddings = embedder.encode(FOOD_DB_RAW, convert_to_numpy=True)

dimension = food_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(food_embeddings)

print(f"✅ FAISS Index built with {index.ntotal} food items.")

def retrieve_relevant_foods(user_query, user_diet, top_k=4):
    """Hybrid Retrieval: Embeds query -> Fetches 20 -> Filters by metadata -> Returns top K"""
    query_vector = embedder.encode([user_query], convert_to_numpy=True)

    # Over-fetch the top 20 mathematically similar items
    distances, indices = index.search(query_vector, top_k * 5)

    retrieved_contexts = []

    for idx in indices[0]:
        allowed_diets = FOOD_METADATA[idx]["allowed_diets"]

        # Metadata Hard Filter: Only keep it if it fits the user's diet
        if user_diet.lower() in allowed_diets:
            retrieved_contexts.append(FOOD_DB_RAW[idx])

            # Stop once we have enough valid foods
            if len(retrieved_contexts) == top_k:
                break

    return retrieved_contexts

import random
import json
from datasets import Dataset

# Updated to include our 13 deficiencies
DEFICIENCIES = [
    "Iron", "Vitamin D", "Vitamin B12", "Calcium", "Zinc",
    "Vitamin C", "Omega-3", "Vitamin A", "Potassium",
    "Magnesium", "Fiber", "Folate", "Protein"
]
DIET_TYPES   = ["vegetarian", "non-vegetarian", "vegan", "jain"]
REGIONS      = ["Delhi", "Punjab", "UP", "Haryana"]

TEMPLATES = [
    "I have {deficiency} deficiency. I am a {diet} from {region}. What should I eat?",
    "Mujhe {deficiency} ki kami hai. Main {region} mein rehta hoon, aur {diet} hoon. Suggest foods.",
    "My doctor found low {deficiency}. I follow a {diet} diet. Give me a plan."
]

def generate_rag_example():
    deficiency = random.choice(DEFICIENCIES)
    diet = random.choice(DIET_TYPES)
    region = random.choice(REGIONS)

    user_query = random.choice(TEMPLATES).format(deficiency=deficiency, diet=diet, region=region)

    # FIX: We now pass user_diet=diet to the retrieval function so the training data is strictly filtered!
    retrieved_docs = retrieve_relevant_foods(f"{deficiency} deficiency for {diet} diet in {region}", user_diet=diet, top_k=3)

    # Fallback just in case a specific diet has zero foods for a nutrient
    if not retrieved_docs:
        context_string = "No perfectly matching foods found. Please suggest standard general advice."
        food_names = ["Standard Supplement"]
    else:
        context_string = "\n".join([f"- {doc}" for doc in retrieved_docs])
        # Extract basic food name for the synthetic JSON output
        food_names = [doc.split(" is ")[0].split(" (")[0] for doc in retrieved_docs]

    output = {
        "deficiency": deficiency,
        "diet_type": diet,
        "region": region,
        "top_foods": [{"name": name} for name in food_names],
        "daily_plan": {
            "morning": f"Include {food_names[0]} in your breakfast." if len(food_names) > 0 else "Take supplement.",
            "lunch": f"Have a portion of {food_names[1]} for lunch." if len(food_names) > 1 else "Have a balanced meal.",
            "evening": f"Consume {food_names[2]} as a snack or side." if len(food_names) > 2 else "Have a healthy snack.",
            "tip": f"Ensure you are eating foods that fit your {diet} diet."
        },
        "weekly_goal": f"Try to eat {food_names[0]} at least 3 times this week." if len(food_names) > 0 else "Maintain your diet.",
        "monthly_milestone": f"Retest your {deficiency} levels after 4 weeks."
    }

    prompt = (
        f"<|im_start|>system\n"
        f"You are NutriSLM, a precise nutrition advisor. "
        f"Use ONLY the provided 'Food Database Context' to answer. "
        f"Create a daily, weekly, and monthly goal plan using these specific foods. "
        f"Always respond in structured JSON format.<|im_end|>\n"
        f"<|im_start|>user\n"
        f"Food Database Context:\n{context_string}\n\n"
        f"User Request: {user_query}<|im_end|>\n"
        f"<|im_start|>assistant\n{json.dumps(output, ensure_ascii=False, indent=2)}<|im_end|>"
    )
    return {"text": prompt}

# Generate a smaller, high-quality dataset teaching the model to read context
print("Generating synthetic RAG training data...")
examples = [generate_rag_example() for _ in range(2500)]
dataset = Dataset.from_list(examples)
split = dataset.train_test_split(test_size=0.1, seed=42)
train_ds, eval_ds = split["train"], split["test"]

print(f"✅ RAG-Aware Dataset generated: {len(train_ds)} train | {len(eval_ds)} eval")

MODEL_ID = "Qwen/Qwen3-0.6B"

print('Loading tokenizer...')
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

print('Loading model in 4-bit (QLoRA)...')
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
model.config.use_cache = False

print('Attaching LoRA adapters...')
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# !pip install mlflow==2.19.0

from trl import SFTTrainer, SFTConfig
import mlflow

mlflow.set_experiment("NutriSLM")

sft_config = SFTConfig(
    output_dir="./nutri_slm_checkpoints",
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,       # effective batch = 16
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    fp16=True,
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=200,
    save_strategy="steps",
    save_steps=200,
    load_best_model_at_end=True,
    max_seq_length=1024,
    dataset_text_field="text",
    report_to="none",                    # change to 'mlflow' to log
    dataloader_num_workers=2,
)

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_ds,
    eval_dataset=eval_ds,
    tokenizer=tokenizer,
)

print('🚀 Starting fine-tuning...')
with mlflow.start_run(run_name="qwen3-0.6b-nutri-v1"):
    mlflow.log_params({
        "model": MODEL_ID, "lora_r": 16, "lora_alpha": 32,
        "lr": 2e-4, "epochs": 3, "train_size": len(train_ds)
    })
    trainer.train()
    mlflow.log_metric("final_train_loss", trainer.state.log_history[-1].get("train_loss", 0))

print('✅ Fine-tuning complete!')

# Save adapter weights
model.save_pretrained("./nutri_slm_adapter")
tokenizer.save_pretrained("./nutri_slm_adapter")
print('✅ Adapter saved to ./nutri_slm_adapter')

import torch
import json
import re

def run_rag_inference(user_input: str, user_diet: str, max_new_tokens: int = 600) -> tuple:

    # 1. Fetch context USING the hybrid metadata filter
    retrieved_docs = retrieve_relevant_foods(user_input, user_diet=user_diet, top_k=4)

    if not retrieved_docs:
        context_string = "No perfectly matching foods found. Please suggest standard general advice."
    else:
        context_string = "\n".join([f"- {doc}" for doc in retrieved_docs])

    # 2. Build the prompt and FORCE the JSON bracket at the end
    prompt = (
        "<|im_start|>system\n"
        "You are NutriSLM, a precise nutrition advisor. "
        "Use ONLY the provided 'Food Database Context' to suggest foods. "
        "Create a daily, weekly, and monthly goal plan using these specific foods. "
        "Always respond in structured JSON format.<|im_end|>\n"
        f"<|im_start|>user\n"
        f"Food Database Context:\n{context_string}\n\n"
        f"User Request: {user_input}<|im_end|>\n"
        "<|im_start|>assistant\n{"
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # --- THE FIX: Calculate the exact length of the prompt ---
    prompt_length = inputs.input_ids.shape[1]

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.2, # Very low temperature for strict JSON formatting
            pad_token_id=tokenizer.eos_token_id,
        )

    # --- THE FIX: Only decode the new tokens the model generated ---
    generated_ids = output_ids[0][prompt_length:]
    generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    # Re-attach the forcing bracket we left in the prompt
    # Re-attach the forcing bracket we left in the prompt
    # Re-attach the forcing bracket we left in the prompt
    full_output = "{" + generated_text

    # --- THE FIX: Mathematical Bracket Counting ---
    try:
        start_idx = full_output.find("{")
        if start_idx == -1:
            raise ValueError("No JSON found")

        brace_count = 0
        end_idx = -1

        # Parse through the text character by character
        for i, char in enumerate(full_output[start_idx:]):
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1

            # When we hit 0, we have found the exact end of the first JSON block
            if brace_count == 0:
                end_idx = start_idx + i + 1
                break

        if end_idx != -1:
            clean_json_string = full_output[start_idx:end_idx]

            # Auto-fix the model's semicolon hallucination
            clean_json_string = clean_json_string.replace("} ;", "},").replace("] ;", "],")

            result_json = json.loads(clean_json_string)
        else:
            raise ValueError("Unclosed JSON brackets")

    except Exception as e:
        # Fallback if it absolutely fails
        result_json = {"raw_output": full_output, "error": str(e)}

    return result_json, context_string

import sqlite3
from datetime import datetime

DB_PATH = "nutri_tracker.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            user_id   TEXT PRIMARY KEY,
            name      TEXT,
            region    TEXT,
            diet_type TEXT,
            created   TEXT
        );
        CREATE TABLE IF NOT EXISTS deficiencies (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id     TEXT,
            deficiency  TEXT,
            severity    TEXT,
            logged_date TEXT
        );
        CREATE TABLE IF NOT EXISTS food_logs (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id   TEXT,
            food_name TEXT,
            meal_time TEXT,
            log_date  TEXT
        );
        CREATE TABLE IF NOT EXISTS goals (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id      TEXT,
            goal_type    TEXT,
            goal_text    TEXT,
            target_date  TEXT,
            completed    INTEGER DEFAULT 0,
            created_date TEXT
        );
    """)
    conn.commit()
    conn.close()

def upsert_user(user_id, name, region, diet_type):
    conn = sqlite3.connect(DB_PATH)
    conn.execute("""
        INSERT OR REPLACE INTO users VALUES (?,?,?,?,?)
    """, (user_id, name, region, diet_type, datetime.now().isoformat()))
    conn.commit(); conn.close()

def log_food(user_id, food_name, meal_time="lunch"):
    conn = sqlite3.connect(DB_PATH)
    conn.execute("INSERT INTO food_logs (user_id,food_name,meal_time,log_date) VALUES (?,?,?,?)",
                 (user_id, food_name, meal_time, datetime.now().date().isoformat()))
    conn.commit(); conn.close()

def save_goals(user_id, plan: dict):
    conn = sqlite3.connect(DB_PATH)
    today = datetime.now().date().isoformat()
    for gtype, gtext in [
        ("daily",   str(plan.get("daily_plan", ""))),
        ("weekly",  plan.get("weekly_goal", "")),
        ("monthly", plan.get("monthly_milestone", "")),
    ]:
        conn.execute("""
            INSERT INTO goals (user_id,goal_type,goal_text,target_date,created_date)
            VALUES (?,?,?,?,?)
        """, (user_id, gtype, gtext, today, today))
    conn.commit(); conn.close()

def get_weekly_summary(user_id):
    conn = sqlite3.connect(DB_PATH)
    rows = conn.execute("""
        SELECT food_name, meal_time, log_date FROM food_logs
        WHERE user_id=? ORDER BY log_date DESC LIMIT 50
    """, (user_id,)).fetchall()
    conn.close()
    return rows

init_db()
print('✅ SQLite tracker DB initialized')

import gradio as gr
import uuid
import json

SESSION = {}

# Expanded to 13 deficiencies
DEFICIENCY_LIST = [
    "Iron", "Vitamin D", "Vitamin B12", "Calcium", "Zinc",
    "Vitamin C", "Omega-3", "Vitamin A", "Potassium",
    "Magnesium", "Fiber", "Folate", "Protein"
]
DIET_LIST  = ["Vegetarian", "Non-vegetarian", "Vegan", "Jain"]
REGION_LIST = ["Delhi", "Punjab", "UP", "Haryana"]

def setup_profile(name, region, diet):
    uid = str(uuid.uuid4())[:8]
    SESSION["user_id"] = uid; SESSION["name"] = name
    SESSION["region"] = region; SESSION["diet_type"] = diet.lower()
    upsert_user(uid, name, region, diet.lower())
    return f"✅ Profile saved! Welcome, {name}. User ID: {uid}"

def get_plan(deficiency, extra_notes):
    if "user_id" not in SESSION:
        return "⚠️ Please set up your profile first (Tab 1).", "", "No context loaded."

    region = SESSION.get("region", "Delhi")
    diet = SESSION.get("diet_type", "vegetarian")

    user_input = f"I have {deficiency} deficiency. I am a {diet} living in {region}. {extra_notes}"

    # FIX: We are now passing user_diet=diet into the inference function!
    result_json, retrieved_context = run_rag_inference(user_input, user_diet=diet)

    save_goals(SESSION["user_id"], result_json)
    pretty = json.dumps(result_json, indent=2, ensure_ascii=False)

    summary = f"## Plan for {deficiency} Deficiency\n\n"
    if "top_foods" in result_json:
        summary += "### Top Foods Suggested\n"
        for f in result_json["top_foods"]:
            summary += f"- **{f['name']}**\n"
    if "daily_plan" in result_json:
        summary += "\n### Daily Plan\n"
        for k, v in result_json["daily_plan"].items():
            summary += f"- **{k.title()}**: {v}\n"
    if "weekly_goal" in result_json:
        summary += f"\n### Weekly Goal\n{result_json['weekly_goal']}\n"

    return summary, pretty, retrieved_context

def log_meal(food_name, meal_time):
    if "user_id" not in SESSION: return "⚠️ Please set up your profile first."
    log_food(SESSION["user_id"], food_name, meal_time)
    return f"✅ Logged: {food_name} at {meal_time}"

with gr.Blocks(title="NutriSLM — RAG Augmented", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🥗 NutriSLM — North India Nutrition Advisor")
    gr.Markdown("*Powered by Qwen3-0.6B + FAISS Vector Database (RAG Architecture)*")

    with gr.Tab("1. Profile"):
        name_in = gr.Textbox(label="Your name")
        region_in = gr.Dropdown(REGION_LIST, label="Region", value="Delhi")
        diet_in = gr.Dropdown(DIET_LIST, label="Diet type", value="Vegetarian")
        save_btn = gr.Button("Save Profile", variant="primary")
        profile_out = gr.Textbox(label="Status", interactive=False)
        save_btn.click(setup_profile, [name_in, region_in, diet_in], profile_out)

    with gr.Tab("2. Nutrition Plan"):
        deficiency_in = gr.Dropdown(DEFICIENCY_LIST, label="Deficiency", value="Iron")
        notes_in = gr.Textbox(label="Notes (Optional)")
        plan_btn = gr.Button("Generate My Plan", variant="primary")

        with gr.Row():
            with gr.Column(scale=2):
                plan_out = gr.Markdown(label="Your Plan")
            with gr.Column(scale=1):
                json_out = gr.Code(label="Model JSON Output", language="json")

        with gr.Accordion("🔍 See How It Works (RAG Vector Context)", open=False):
            gr.Markdown("This is the factual data pulled from the FAISS database and injected into the LLM prompt to prevent hallucination:")
            context_out = gr.Textbox(label="Retrieved Context", lines=5, interactive=False)

        plan_btn.click(get_plan, [deficiency_in, notes_in], [plan_out, json_out, context_out])

    with gr.Tab("3. Log Food"):
        food_in = gr.Textbox(label="Food name")
        meal_in = gr.Dropdown(["morning", "lunch", "evening", "dinner"], value="lunch")
        log_btn = gr.Button("Log Food", variant="primary")
        log_out = gr.Textbox(label="Status", interactive=False)
        log_btn.click(log_meal, [food_in, meal_in], log_out)

# Note: Added inline=False so the UI is cleaner
demo.launch(share=True, inline=False)